[theme]
base="dark"
primaryColor="#6C63FF"
backgroundColor="#1E1E2F"
secondaryBackgroundColor="#2C2C3A"
textColor="#FFFFFF"
font="sans serif"

[server]
headless=true
enableCORS=false
enableXsrfProtection=false
